[package]
name = "hid-gamepad-types"
license = "MIT"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.7"
cgmath = { version = "0.18", default-features = false }
